plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-sources.cjs

packageExtensions:
  'astroturf@*':
    dependencies:
      react: '^17.0.0'
      webpack: '^5.20.0'
