name: Renovate

on:
  schedule:
    - cron: '0 */3 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2.3.4
      - name: Run renovate
        uses: renovatebot/github-action@v27.5.0
        env:
          LOG_LEVEL: debug
        with:
          configurationFile: config/renovate-self-hosted.json
          token: ${{ secrets.RENOVATE_TOKEN }}
