name: Renovate
on:
  schedule:
    - cron: '0 */3 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: renovatebot/github-action@v24.110.0
        env:
          LOG_LEVEL: debug
        with:
          configurationFile: config/renovate-self-hosted.json
          token: ${{ secrets.RENOVATE_TOKEN }}
